version: "3"

tasks:
    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/blackops main.go 

    run: 
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run main.go
        - GOFLAGS=-mod=mod go run main.go get --help

    # clean:
    #     desc: Remove all retrieved *.png files
    #     cmds:
    #     - rm *.png